[package]
name = "optea-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "optea"
path = "src/main.rs"

[dependencies]
optea-sys.workspace = true
optea-core.workspace = true
optea-metrics.workspace = true
optea-game.workspace = true
anyhow.workspace = true
serde_json.workspace = true
