[package]
name = "optea-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
optea-sys.workspace = true
optea-game.workspace = true
optea-metrics.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
time.workspace = true
